export interface PlantGuide {
  type: string
  emoji: string
  wateringFrequency: number
  quickTips: string[]
  sunlight: string
  soil: string
  harvestTime?: string
  careInstructions?: string
  fertilizingSchedule?: string
  pruningTips?: string
  commonPests?: string
  growthStages?: string
}

export const plantGuides: Record<string, PlantGuide> = {
  'Olive Tree': {
    type: 'Olive Tree',
    emoji: '🫒',
    wateringFrequency: 7,
    quickTips: [
      'Water deeply but infrequently',
      'Needs full sun (6-8 hours daily)',
      'Requires well-draining soil (pH 5.5-8.5)',
      'Prune in late winter (February-March)',
      'Takes 5-8 years to produce fruit',
      'Protect from frost in winter',
    ],
    sunlight: 'Full sun (6-8 hours daily)',
    soil: 'Well-draining, sandy loam, pH 5.5-8.5',
    harvestTime: 'Fall (September-November)',
    careInstructions: 'Requires patience as growth is slow. Protect from frost and extreme cold. Water deeply to encourage deep root growth.',
    fertilizingSchedule: 'Apply nitrogen-rich fertilizer in early spring and late summer. Avoid fertilizing in late autumn.',
    pruningTips: 'Prune in late winter (Feb-March) to maintain shape, remove dead wood, and open the canopy for light.',
    commonPests: 'Olive fruit fly, scale insects, peacock spot (fungal disease).',
    growthStages: 'Slow growing. First fruit typically after 3-5 years. Full production 7-9 years.',
  },
  'Tomato': {
    type: 'Tomato',
    emoji: '🍅',
    wateringFrequency: 2,
    quickTips: [
      'Water every 2 days, keep soil consistently moist',
      'Requires 6-8 hours of full sun',
      'Support with stakes or cages',
      'Pinch off suckers for better fruit production',
      'Harvest when fully colored and slightly soft',
      'Check for hornworms and aphids regularly',
    ],
    sunlight: 'Full sun (6-8 hours minimum)',
    soil: 'Rich, well-draining, pH 6.0-6.8',
    harvestTime: '60-80 days after transplanting',
    careInstructions: 'Support plants with stakes or cages immediately after planting. Mulch to retain moisture and prevent soil-borne diseases.',
    fertilizingSchedule: 'Balanced fertilizer at planting. Switch to low-nitrogen, high-phosphorus fertilizer when flowering starts.',
    pruningTips: 'Remove "suckers" (shoots between stem and branch) to focus energy on fruit. Remove lower leaves to improve air circulation.',
    commonPests: 'Tomato hornworms, aphids, whiteflies, early/late blight, blossom end rot.',
    growthStages: 'Seedling -> Vegetative Growth -> Flowering -> Fruit Set -> Ripening (60-80 days total).',
  },
  'Cucumber': {
    type: 'Cucumber',
    emoji: '🥒',
    wateringFrequency: 1,
    quickTips: [
      'Water daily, needs consistent moisture',
      'Requires full sun and warm weather',
      'Provide trellis for vertical growth',
      'Harvest when 6-8 inches long',
      'Pick daily at peak season to encourage production',
      'Watch for powdery mildew on leaves',
    ],
    sunlight: 'Full sun (6-8 hours daily)',
    soil: 'Rich, loose soil, pH 6.0-7.0',
    harvestTime: '50-70 days from planting',
    careInstructions: 'Avoid wetting leaves when watering to prevent mildew. Train vines up a trellis for cleaner fruit and better airflow.',
    fertilizingSchedule: 'Mix compost into soil before planting. Side dress with balanced fertilizer when first flowers appear.',
    pruningTips: 'Prune main stem after 7 leaves if not trellising to encourage side shoots. Remove yellowing lower leaves.',
    commonPests: 'Cucumber beetles, aphids, squash bugs, powdery mildew.',
    growthStages: 'Fast growing. Flowering starts 35-45 days. Harvest 50-70 days.',
  },
  'Pepper': {
    type: 'Pepper',
    emoji: '🫑',
    wateringFrequency: 2,
    quickTips: [
      'Water every 2 days, deeply and regularly',
      'Needs full sun and warm temperatures (70-85°F)',
      'Pinch first flowers for stronger plant',
      'Add calcium to prevent blossom end rot',
      'Harvest green or wait for color change',
      'Stake plants when fruit appears',
    ],
    sunlight: 'Full sun (6-8 hours), warm temps',
    soil: 'Well-draining, nutrient-rich, pH 6.0-6.8',
    harvestTime: 'Green: 60-80 days, Colored: 80-100 days',
    careInstructions: 'Keep plants warm. Stake if heavy fruit load causes bending. Mulch to maintain even soil moisture.',
    fertilizingSchedule: 'Balanced fertilizer. Avoid excessive nitrogen which reduces fruit set. Add magnesium (Epsom salts) if leaves yellow.',
    pruningTips: 'Pinch off early flowers to encourage stronger vegetative growth first. Prune bottom leaves to prevent soil splash.',
    commonPests: 'Aphids, spider mites, flea beetles, blossom end rot (calcium deficiency).',
    growthStages: 'Slow establishment -> Flowering -> Fruiting -> Ripening (60-90 days).',
  },
  'Carrot': {
    type: 'Carrot',
    emoji: '🥕',
    wateringFrequency: 2,
    quickTips: [
      'Water regularly to keep soil evenly moist',
      'Needs loose, deep soil for straight root growth',
      'Direct sow - does not transplant well',
      'Thin seedlings to 2-3 inches apart',
      'Remove stones from soil before planting',
      'Harvest when tops are visible above soil',
    ],
    sunlight: 'Full sun to partial shade',
    soil: 'Loose, deep, sandy soil, pH 6.0-6.8',
    harvestTime: '60-80 days from seed',
    careInstructions: 'Keep soil surface moist for germination (can take 2-3 weeks). Weed carefully to avoid disturbing roots.',
    fertilizingSchedule: 'Low nitrogen, high potassium/phosphate for root development. Avoid fresh manure (causes forking).',
    pruningTips: 'Thin seedlings aggressively to 2-3 inches apart to prevent overcrowding and small roots.',
    commonPests: 'Carrot rust fly, wireworms, parsley worms.',
    growthStages: 'Germination (slow) -> Leaf growth -> Root enlargement -> Harvest.',
  },
  'Lettuce': {
    type: 'Lettuce',
    emoji: '🥬',
    wateringFrequency: 1,
    quickTips: [
      'Water daily in warm weather, keep soil moist',
      'Prefers cooler temperatures (60-70°F)',
      'Tolerates partial shade, especially in summer',
      'Harvest outer leaves continuously',
      'Bolts (goes to seed) in hot weather',
      'Plant in succession every 2 weeks',
    ],
    sunlight: 'Full sun to partial shade',
    soil: 'Rich, moist soil, pH 6.0-7.0',
    harvestTime: '30-60 days from planting',
    careInstructions: 'Keep cool and moist. Use shade cloth in hot summer months. Mulch to keep soil cool.',
    fertilizingSchedule: 'Nitrogen-rich fertilizer or compost tea every 2-3 weeks for leafy growth.',
    pruningTips: 'Harvest outer leaves (cut-and-come-again) or cut entire head. Remove bolting (flowering) stalks immediately.',
    commonPests: 'Slugs, snails, aphids, cutworms.',
    growthStages: 'Fast germination -> Leaf rosette -> Harvest -> Bolting (seed production).',
  },
  'Herbs': {
    type: 'Herbs',
    emoji: '🌿',
    wateringFrequency: 2,
    quickTips: [
      'Most herbs prefer moderate watering',
      'Need excellent drainage to prevent root rot',
      'Harvest regularly to encourage bushy growth',
      'Varies by herb type (basil, mint, oregano, etc.)',
      'Most need 4-6 hours of direct sun',
      'Pinch flowers to prolong leaf production',
    ],
    sunlight: '4-6 hours of sun daily',
    soil: 'Well-draining, pH 6.0-7.0',
    harvestTime: 'Continuous harvest after establishment',
    careInstructions: 'Avoid overwatering. Most herbs prefer slightly dry conditions between waterings. Ensure good air circulation.',
    fertilizingSchedule: 'Light feeding only. Too much fertilizer reduces flavor and aroma.',
    pruningTips: 'Harvest frequently. Pinch back growing tips to encourage bushiness. Remove flowers to prolong life.',
    commonPests: 'Aphids, spider mites, whiteflies.',
    growthStages: 'Varies. Most are ready for light harvest in 3-4 weeks from transplant.',
  },
  'Other': {
    type: 'Other',
    emoji: '🌱',
    wateringFrequency: 3,
    quickTips: [
      'Research your specific plant type thoroughly',
      'Check sunlight requirements for your plant',
      'Understand watering needs (frequency and amount)',
      'Learn about common pests and diseases',
      'Know the expected growth timeline',
      'Join gardening communities for specific advice',
    ],
    sunlight: 'Varies by plant type',
    soil: 'Varies by plant type',
    harvestTime: 'Varies by plant type',
    careInstructions: 'Research specific care requirements for this plant species.',
    fertilizingSchedule: 'Varies by plant type.',
    pruningTips: 'Remove dead or diseased parts. Research specific pruning needs.',
    commonPests: 'Monitor for common garden pests.',
    growthStages: 'Varies by plant type.',
  },
}
